DROP TABLE BS_ALARM;

CREATE TABLE BS_ALARM (ALARMNO NUMBER PRIMARY KEY, USERNO NUMBER REFERENCES BS_USER(USERNO),BABYNO NUMBER REFERENCES BS_BABY(BABYNO), ALARMTITLE VARCHAR2(100),ALARMTYPE INTEGER,ALARMAMOUNT INTEGER, ALARMTIME DATE,ENDTIME DATE);

INSERT INTO BS_ALARM VALUES(0,0,0,'테스트일정',0 ,TO_DATE('2018-08-09/16:00:00','YYYY-MM-DD/HH24:MI:SS'));

DROP SEQUENCS BS_ALARMSEQ;

CREATE SEQUENCE BS_ALARMSEQ;

기타	모유	젖병	이유식	유축	배소변 	수면	목욕
0	1	2	3		4	5		6	7

