DROP TABLE FRIEND;

DROP TABLE SNS;

DROP TABLE SNS_REPLY;

CREATE TABLE FRIEND (USERNO NUMBER REFERENCES BS_USER(USERNO), FRIEND NUMBER REFERENCES BS_USER(USERNO));

CREATE TABLE SNS (SNSNO NUMBER PRIMARY KEY, USERNO NUMBER REFERENCES BS_USER(USERNO),USERNICK VARCHAR2(30),PERMISSION NUMBER,CONTENT VARCHAR2(2000), LIKEY NUMBER,
PHOTOCOUNT NUMBER, PHOTO_1 VARCHAR2(200),PHOTO_2 VARCHAR2(200),PHOTO_3 VARCHAR2(200),PHOTO_4 VARCHAR2(200), WRITEDATE DATE);

CREATE TABLE SNS_REPLY (RPLYNO NUMBER PRIMARY KEY, USERNO NUMBER,USERNICK VARCHAR2(30) ,CONTENT VARCHAR2(2000), PARENT_RPLY NUMBER ,WRITEDATE DATE);

DROP SEQUENCE FRIEND_SEQ;

DROP SEQUENCE SNS_SEQ;

DROP SEQUENCE SNS_RPLY_SEQ;

CREATE SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE SNS_SEQ;

CREATE SEQUENCE SNS_RPLY_SEQ;

CREATE TABLE SINGO(SNSNO NUMBER, USERNO NUMBER);