DROP TABLE FRIEND;

DROP TABLE SNS;

DROP TABLE SNS_REPLY;

CREATE TABLE FRIEND (USERNO NUMBER REFERENCES BS_USER(USERNO), FRIEND NUMBER REFERENCES BS_USER(USERNO));

CREATE TABLE SNS (SNSNO NUMBER PRIMARY KEY, USERNO NUMBER REFERENCES BS_USER(USERNO),PERMISSION NUMBER,CONTENT VARCHAR2(2000), LIKEY NUMBER,
PHOTOCOUNT NUMBER, PHOTOGROUP VARCHAR2(2000), WRITEDATE DATE);

CREATE TABLE SNS_REPLY (RPLYNO NUMBER PRIMARY KEY, USERNO NUMBER ,CONTENT VARCHAR2(2000), PARENT_RPLY NUMBER ,WRITE_DATE DATE);

DROP SEQUENCE FRIEND_SEQ;

DROP SEQUENCE SNS_SEQ;

DROP SEQUENCE SNS_RPLY_SEQ;

CREATE SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE SNS_SEQ;

CREATE SEQUENCE SNS_RPLY_SEQ;